export type ResidencyStatus = 'citizen' | 'pr' | 'foreigner'
export type PropertyNumber = 1 | 2 | 3
export type PropertyType = 'private' | 'hdb'

export interface PropertyInputs {
  price: number
  residencyStatus: ResidencyStatus
  propertyType: PropertyType
  propertyNumber: PropertyNumber
  expectedRentalYield: number
  holdingPeriodYears: number
  annualAppreciation: number
  loanPercentage: number
  loanInterestRate: number
  loanTenureYears: number
  monthlyIncome: number
  monthlyCondoFees: number
  isRentingOut: boolean
  cashAvailable: number
  cpfOaBalance: number
  useCpfForDownpayment: boolean
  useCpfForMonthly: boolean
  existingMonthlyDebt: number
  marginalTaxRate: number
  currentMonthlyRent: number
  expectedMonthlyRental: number
  rentOutRoom: boolean
  roomRentalIncome: number
  annualWorkIncome: number
  agentFeePercent: number
  prevailingInterestRate: number
  loanLockInYears: number
  includeRenovation: boolean
  renovationCost: number
  vacancyWeeksPerYear: number
}

export interface CalculationResults {
  bsd: number
  absd: number
  absdRate: number
  legalFees: number
  valuationFee: number
  stampDutyOnMortgage: number
  totalStampDuty: number
  totalUpfrontCosts: number
  loanAmount: number
  downPayment: number
  monthlyPayment: number
  totalInterestPaid: number
  cashNeeded: number
  annualRentalIncome: number
  monthlyRentalIncome: number
  annualPropertyTax: number
  annualMaintenance: number
  annualNetRental: number
  monthlyNetRental: number
  futureValue: number
  capitalGain: number
  totalRentalIncome: number
  holdingCosts: number
  interestDuringHolding: number
  sellingCosts: number
  agentCommission: number
  netProfit: number
  roi: number
  annualizedRoi: number
  stockReturn: number
  bondReturn: number
  savingsReturn: number
  reitReturn: number
  totalInvestment: number
  ssd: number
  ssdApplies: boolean
  breakEvenPrice: number
  tdsr: number
  tdsrOk: boolean
  cpfUsedForDownpayment: number
  cashForDownpayment: number
  totalCpfUsed: number
  cpfAccruedInterest: number
  totalCpfRefund: number
  cpfReturn: number
  annualRentalTax: number
  totalRentalTax: number
  annualRoomTax: number
  canAfford: boolean
  shortfall: number
  totalCashInvestment: number
  minCashDownpayment: number
  maxAffordablePrice: number
  affordabilityRatio: number
  isStretched: boolean
  isOverStretched: boolean
  tdsrRemaining: number
  monthlySavedRent: number
  annualSavedRent: number
  totalSavedRent: number
  monthlyRoomIncome: number
  annualRoomIncome: number
  totalRoomIncome: number
  annualNetCashflow: number
  pvCashflows: number
  fvCashflows: number
  remainingLoan: number
  salesIncome: number
  totalReturn: number
  totalAppreciationPercent: number
  totalLoanPayments: number
  totalIncomeFromProperty: number
  fireInsurance: number
  homeInsurance: number
  annualInsurance: number
  vacancyLoss: number
  totalVacancyLoss: number
  effectiveAnnualRental: number
  sellingLegalFees: number
  earlyRepaymentPenalty: number
  annualRepairs: number
  annualCondoFees: number
}
